// Code generated by qtc from "basepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/basepage.qtpl:1
package templates

//line templates/basepage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/basepage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/basepage.qtpl:2
type Page interface {
//line templates/basepage.qtpl:2
	Lang() string
//line templates/basepage.qtpl:2
	StreamLang(qw422016 *qt422016.Writer)
//line templates/basepage.qtpl:2
	WriteLang(qq422016 qtio422016.Writer)
//line templates/basepage.qtpl:2
	Title() string
//line templates/basepage.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/basepage.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/basepage.qtpl:2
	Body() string
//line templates/basepage.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line templates/basepage.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line templates/basepage.qtpl:2
	Style() string
//line templates/basepage.qtpl:2
	StreamStyle(qw422016 *qt422016.Writer)
//line templates/basepage.qtpl:2
	WriteStyle(qq422016 qtio422016.Writer)
//line templates/basepage.qtpl:2
	Scripts() string
//line templates/basepage.qtpl:2
	StreamScripts(qw422016 *qt422016.Writer)
//line templates/basepage.qtpl:2
	WriteScripts(qq422016 qtio422016.Writer)
//line templates/basepage.qtpl:2
}

//line templates/basepage.qtpl:11
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line templates/basepage.qtpl:11
	qw422016.N().S(`
<!DOCTYPE html>
<html lang="`)
//line templates/basepage.qtpl:13
	p.StreamLang(qw422016)
//line templates/basepage.qtpl:13
	qw422016.N().S(`">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>`)
//line templates/basepage.qtpl:18
	p.StreamTitle(qw422016)
//line templates/basepage.qtpl:18
	qw422016.N().S(`</title>
    <style>
    `)
//line templates/basepage.qtpl:20
	qw422016.N().S(`
        html, body{
            padding:0;
            margin:0;
            width:100%;
            height: 100%;
        }
        `)
//line templates/basepage.qtpl:27
	qw422016.N().S(`
        `)
//line templates/basepage.qtpl:28
	p.StreamStyle(qw422016)
//line templates/basepage.qtpl:28
	qw422016.N().S(`
    </style>
</head>
	<body>
	  `)
//line templates/basepage.qtpl:32
	p.StreamBody(qw422016)
//line templates/basepage.qtpl:32
	qw422016.N().S(`
      <script>
     `)
//line templates/basepage.qtpl:34
	p.StreamScripts(qw422016)
//line templates/basepage.qtpl:34
	qw422016.N().S(`
     </script>
	</body>
</html>
`)
//line templates/basepage.qtpl:38
}

//line templates/basepage.qtpl:38
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line templates/basepage.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/basepage.qtpl:38
	StreamPageTemplate(qw422016, p)
//line templates/basepage.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line templates/basepage.qtpl:38
}

//line templates/basepage.qtpl:38
func PageTemplate(p Page) string {
//line templates/basepage.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/basepage.qtpl:38
	WritePageTemplate(qb422016, p)
//line templates/basepage.qtpl:38
	qs422016 := string(qb422016.B)
//line templates/basepage.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/basepage.qtpl:38
	return qs422016
//line templates/basepage.qtpl:38
}

//line templates/basepage.qtpl:41
type BasePage struct {
}

//line templates/basepage.qtpl:44
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/basepage.qtpl:44
	qw422016.N().S(`This is a base title`)
//line templates/basepage.qtpl:44
}

//line templates/basepage.qtpl:44
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/basepage.qtpl:44
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/basepage.qtpl:44
	p.StreamTitle(qw422016)
//line templates/basepage.qtpl:44
	qt422016.ReleaseWriter(qw422016)
//line templates/basepage.qtpl:44
}

//line templates/basepage.qtpl:44
func (p *BasePage) Title() string {
//line templates/basepage.qtpl:44
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/basepage.qtpl:44
	p.WriteTitle(qb422016)
//line templates/basepage.qtpl:44
	qs422016 := string(qb422016.B)
//line templates/basepage.qtpl:44
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/basepage.qtpl:44
	return qs422016
//line templates/basepage.qtpl:44
}

//line templates/basepage.qtpl:45
func (p *BasePage) StreamLang(qw422016 *qt422016.Writer) {
//line templates/basepage.qtpl:45
	qw422016.N().S(`ru`)
//line templates/basepage.qtpl:45
}

//line templates/basepage.qtpl:45
func (p *BasePage) WriteLang(qq422016 qtio422016.Writer) {
//line templates/basepage.qtpl:45
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/basepage.qtpl:45
	p.StreamLang(qw422016)
//line templates/basepage.qtpl:45
	qt422016.ReleaseWriter(qw422016)
//line templates/basepage.qtpl:45
}

//line templates/basepage.qtpl:45
func (p *BasePage) Lang() string {
//line templates/basepage.qtpl:45
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/basepage.qtpl:45
	p.WriteLang(qb422016)
//line templates/basepage.qtpl:45
	qs422016 := string(qb422016.B)
//line templates/basepage.qtpl:45
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/basepage.qtpl:45
	return qs422016
//line templates/basepage.qtpl:45
}

//line templates/basepage.qtpl:46
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/basepage.qtpl:46
	qw422016.N().S(`This is a base body`)
//line templates/basepage.qtpl:46
}

//line templates/basepage.qtpl:46
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/basepage.qtpl:46
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/basepage.qtpl:46
	p.StreamBody(qw422016)
//line templates/basepage.qtpl:46
	qt422016.ReleaseWriter(qw422016)
//line templates/basepage.qtpl:46
}

//line templates/basepage.qtpl:46
func (p *BasePage) Body() string {
//line templates/basepage.qtpl:46
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/basepage.qtpl:46
	p.WriteBody(qb422016)
//line templates/basepage.qtpl:46
	qs422016 := string(qb422016.B)
//line templates/basepage.qtpl:46
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/basepage.qtpl:46
	return qs422016
//line templates/basepage.qtpl:46
}

//line templates/basepage.qtpl:47
func (p *BasePage) StreamStyle(qw422016 *qt422016.Writer) {
//line templates/basepage.qtpl:47
	qw422016.N().S(`This is a base css`)
//line templates/basepage.qtpl:47
}

//line templates/basepage.qtpl:47
func (p *BasePage) WriteStyle(qq422016 qtio422016.Writer) {
//line templates/basepage.qtpl:47
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/basepage.qtpl:47
	p.StreamStyle(qw422016)
//line templates/basepage.qtpl:47
	qt422016.ReleaseWriter(qw422016)
//line templates/basepage.qtpl:47
}

//line templates/basepage.qtpl:47
func (p *BasePage) Style() string {
//line templates/basepage.qtpl:47
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/basepage.qtpl:47
	p.WriteStyle(qb422016)
//line templates/basepage.qtpl:47
	qs422016 := string(qb422016.B)
//line templates/basepage.qtpl:47
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/basepage.qtpl:47
	return qs422016
//line templates/basepage.qtpl:47
}

//line templates/basepage.qtpl:48
func (p *BasePage) StreamScripts(qw422016 *qt422016.Writer) {
//line templates/basepage.qtpl:48
	qw422016.N().S(`This is a base js`)
//line templates/basepage.qtpl:48
}

//line templates/basepage.qtpl:48
func (p *BasePage) WriteScripts(qq422016 qtio422016.Writer) {
//line templates/basepage.qtpl:48
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/basepage.qtpl:48
	p.StreamScripts(qw422016)
//line templates/basepage.qtpl:48
	qt422016.ReleaseWriter(qw422016)
//line templates/basepage.qtpl:48
}

//line templates/basepage.qtpl:48
func (p *BasePage) Scripts() string {
//line templates/basepage.qtpl:48
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/basepage.qtpl:48
	p.WriteScripts(qb422016)
//line templates/basepage.qtpl:48
	qs422016 := string(qb422016.B)
//line templates/basepage.qtpl:48
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/basepage.qtpl:48
	return qs422016
//line templates/basepage.qtpl:48
}
