// Code generated by qtc from "mainpage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/mainpage.qtpl:1
package templates

//line templates/mainpage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/mainpage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/mainpage.qtpl:2
type MainPage struct {
	Locale   []byte
	Prefix   []byte
	Redirect []byte
	App      []byte
	Error    []byte
}

//line templates/mainpage.qtpl:10
func (p *MainPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:10
	qw422016.N().S(`УМП Логин`)
//line templates/mainpage.qtpl:10
}

//line templates/mainpage.qtpl:10
func (p *MainPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:10
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:10
	p.StreamTitle(qw422016)
//line templates/mainpage.qtpl:10
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:10
}

//line templates/mainpage.qtpl:10
func (p *MainPage) Title() string {
//line templates/mainpage.qtpl:10
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:10
	p.WriteTitle(qb422016)
//line templates/mainpage.qtpl:10
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:10
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:10
	return qs422016
//line templates/mainpage.qtpl:10
}

//line templates/mainpage.qtpl:11
func (p *MainPage) StreamLang(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:11
	qw422016.E().Z(p.Locale)
//line templates/mainpage.qtpl:11
}

//line templates/mainpage.qtpl:11
func (p *MainPage) WriteLang(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:11
	p.StreamLang(qw422016)
//line templates/mainpage.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:11
}

//line templates/mainpage.qtpl:11
func (p *MainPage) Lang() string {
//line templates/mainpage.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:11
	p.WriteLang(qb422016)
//line templates/mainpage.qtpl:11
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:11
	return qs422016
//line templates/mainpage.qtpl:11
}

//line templates/mainpage.qtpl:12
func (p *MainPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:12
	qw422016.N().S(`
 <main class="main">
        <form id="loginForm" class="loginForm" action="`)
//line templates/mainpage.qtpl:14
	qw422016.E().Z(p.Prefix)
//line templates/mainpage.qtpl:14
	qw422016.N().S(`/login" method="post">
        <input type="hidden" name="app" value="`)
//line templates/mainpage.qtpl:15
	qw422016.N().UZ(p.App)
//line templates/mainpage.qtpl:15
	qw422016.N().S(`" >
        <input type="hidden" name="redirect" value="`)
//line templates/mainpage.qtpl:16
	qw422016.N().UZ(p.Redirect)
//line templates/mainpage.qtpl:16
	qw422016.N().S(`" >
            <div class="loginForm__row">
                <label class="loginForm__label" for="username">Username</label><input class="loginForm__input" type="text" id="username" name="username">
            </div>
            <div class="loginForm__row">
                <label class="loginForm__label" for="password">Password</label><input class="loginForm__input" type="text" id="password" name="password">
            </div>
            `)
//line templates/mainpage.qtpl:23
	StreamErr(qw422016, p.Error)
//line templates/mainpage.qtpl:23
	qw422016.N().S(`
            <div class="loginForm__row loginForm__row--submit">
                <button type="submit">Submit</button>
            </div>
        </form>
    </main>
`)
//line templates/mainpage.qtpl:29
}

//line templates/mainpage.qtpl:29
func (p *MainPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:29
	p.StreamBody(qw422016)
//line templates/mainpage.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:29
}

//line templates/mainpage.qtpl:29
func (p *MainPage) Body() string {
//line templates/mainpage.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:29
	p.WriteBody(qb422016)
//line templates/mainpage.qtpl:29
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:29
	return qs422016
//line templates/mainpage.qtpl:29
}

//line templates/mainpage.qtpl:30
func (p *MainPage) StreamStyle(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:30
	qw422016.N().S(`
.main{
            width: 100vw;
            height: 100vh;
            overflow: hidden;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        .loginForm{
            border: 1px solid #ccc;
            padding: 16px;
            display: flex;
            flex-direction: column;
        }
        .loginForm__row{
            display: flex;
            margin: 10px 0;
        }
        .loginForm__label{
            width: 100px;
        }
        .loginForm__input{
            width: 150px;
        }
        .loginForm__row--submit{
            justify-content: flex-end;
        }
`)
//line templates/mainpage.qtpl:58
}

//line templates/mainpage.qtpl:58
func (p *MainPage) WriteStyle(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:58
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:58
	p.StreamStyle(qw422016)
//line templates/mainpage.qtpl:58
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:58
}

//line templates/mainpage.qtpl:58
func (p *MainPage) Style() string {
//line templates/mainpage.qtpl:58
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:58
	p.WriteStyle(qb422016)
//line templates/mainpage.qtpl:58
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:58
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:58
	return qs422016
//line templates/mainpage.qtpl:58
}

//line templates/mainpage.qtpl:59
func (p *MainPage) StreamScripts(qw422016 *qt422016.Writer) {
//line templates/mainpage.qtpl:59
	qw422016.N().S(`
 (function(){
            const $form = document.getElementById("loginForm");
            const $username = document.getElementById("username");
            const $password = document.getElementById("password");

            $form.addEventListener("submit", (e)=>{
               
                if (!$username.value.trim() || !$password.value.trim()){
                    e.preventDefault();
                    return;
                }
            });
        })()
`)
//line templates/mainpage.qtpl:73
}

//line templates/mainpage.qtpl:73
func (p *MainPage) WriteScripts(qq422016 qtio422016.Writer) {
//line templates/mainpage.qtpl:73
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:73
	p.StreamScripts(qw422016)
//line templates/mainpage.qtpl:73
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:73
}

//line templates/mainpage.qtpl:73
func (p *MainPage) Scripts() string {
//line templates/mainpage.qtpl:73
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:73
	p.WriteScripts(qb422016)
//line templates/mainpage.qtpl:73
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:73
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:73
	return qs422016
//line templates/mainpage.qtpl:73
}

//line templates/mainpage.qtpl:75
func StreamErr(qw422016 *qt422016.Writer, err []byte) {
//line templates/mainpage.qtpl:75
	qw422016.N().S(`
`)
//line templates/mainpage.qtpl:76
	if len(err) > 0 {
//line templates/mainpage.qtpl:76
		qw422016.N().S(`
    <div class="loginForm__row--error">
        `)
//line templates/mainpage.qtpl:78
		qw422016.E().Z(err)
//line templates/mainpage.qtpl:78
		qw422016.N().S(`    
    </div>
`)
//line templates/mainpage.qtpl:80
	}
//line templates/mainpage.qtpl:80
	qw422016.N().S(`
`)
//line templates/mainpage.qtpl:81
}

//line templates/mainpage.qtpl:81
func WriteErr(qq422016 qtio422016.Writer, err []byte) {
//line templates/mainpage.qtpl:81
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/mainpage.qtpl:81
	StreamErr(qw422016, err)
//line templates/mainpage.qtpl:81
	qt422016.ReleaseWriter(qw422016)
//line templates/mainpage.qtpl:81
}

//line templates/mainpage.qtpl:81
func Err(err []byte) string {
//line templates/mainpage.qtpl:81
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/mainpage.qtpl:81
	WriteErr(qb422016, err)
//line templates/mainpage.qtpl:81
	qs422016 := string(qb422016.B)
//line templates/mainpage.qtpl:81
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/mainpage.qtpl:81
	return qs422016
//line templates/mainpage.qtpl:81
}
